# site name
prefixName: Jason
siteName: 个人博客
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/others/avatar.jpg
url: https://zhizunjiege.github.io
description: 仰望星空，脚踏实地。
cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 个人博客站点，不定期更新，左下角有音乐播放器，边听歌边看吧~~~
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives/, fa: fa-archive faa-shake }
  分类: { path: javascript:;, fa: fa-list-ul faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code },
    资源: {path: /categories/资源/, fa: fa-cloud-download } 
    # 转载: {path: /categories/转载/, fa: fa-book },
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o }
  } }
  标签: { path: javascript:;, fa: fa-tags faa-vertical, submenus: { 
    # 书籍: {path: /tags/书籍/, fa: fa-th-list faa-bounce },
    # 音乐: {path: /tags/音乐/, fa: fa-headphones },
    # 图片: {path: /tags/图片/, fa: fa-photo }
    软件: {path: /tags/软件/, fa: fa-linux },
    记录: {path: /tags/记录/, fa: fa-pencil-square-o }
  } }
  追番: {path: /bangumi/, fa: fa-film faa-vertical }
  # 留言: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友链: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: {path: /about/, fa: fa-meetup}
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  #   我？: {path: /about/, fa: fa-meetup}, 
  #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #   Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - /img/bg/bg-1.webp
  - /img/bg/bg-2.webp
  - /img/bg/bg-3.webp
  - /img/bg/bg-4.webp
  - /img/bg/bg-5.webp
  - /img/bg/bg-6.webp
  - /img/bg/bg-7.webp
  - /img/bg/bg-8.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  # - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/22867237, title: Bilibili, desc: Bilibili个人空间, img: /img/others/bilibili.webp}
  - {url: /, title: Jasonの个人博客, desc: 不定期更新, img: /img/others/blog.webp}



# your site build time or founded date
siteBuildingTime: 06/14/2020

#social  url, img PC端配置
social:
  github: {url: https://github.com/zhizunjiege, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  netease: {url: https://music.163.com/#/user/home?id=553291867, img: /img/social/wangyiyun.png}
  # zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:2452816044@qq.com, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.png, img: /img/social/wechat.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/zhizunjiege, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2452816044&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  # paypal: https://www.paypal.me/hojuncn
  alipay: /img/donate/AliPayQR.jpg
  wechat: /img/donate/WeChatQR.png
  wechatSQ: /img/donate/WeChatQR.png
  # wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: 
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: 

aplayer: 
  id: 5065571633
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.4
  mutex: true

# Valine
valine: false
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

