/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/那些令人惊艳的Hexo主题': RouteRecordInfo<'/posts/那些令人惊艳的Hexo主题', '/posts/那些令人惊艳的Hexo主题', Record<never, never>, Record<never, never>>,
    '/posts/推荐两款chrome插件': RouteRecordInfo<'/posts/推荐两款chrome插件', '/posts/推荐两款chrome插件', Record<never, never>, Record<never, never>>,
    '/posts/一键评教脚本': RouteRecordInfo<'/posts/一键评教脚本', '/posts/一键评教脚本', Record<never, never>, Record<never, never>>,
    '/posts/用于mingw-w64的opencv4编译指南及资源': RouteRecordInfo<'/posts/用于mingw-w64的opencv4编译指南及资源', '/posts/用于mingw-w64的opencv4编译指南及资源', Record<never, never>, Record<never, never>>,
    '/posts/这半年': RouteRecordInfo<'/posts/这半年', '/posts/这半年', Record<never, never>, Record<never, never>>,
    '/posts/Kirikiroid2使用指南': RouteRecordInfo<'/posts/Kirikiroid2使用指南', '/posts/Kirikiroid2使用指南', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
