/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/chrome-extensions': RouteRecordInfo<'/posts/chrome-extensions', '/posts/chrome-extensions', Record<never, never>, Record<never, never>>,
    '/posts/compile-opencv4-with-mingw-w64': RouteRecordInfo<'/posts/compile-opencv4-with-mingw-w64', '/posts/compile-opencv4-with-mingw-w64', Record<never, never>, Record<never, never>>,
    '/posts/half-of-this-year': RouteRecordInfo<'/posts/half-of-this-year', '/posts/half-of-this-year', Record<never, never>, Record<never, never>>,
    '/posts/hexo-themes': RouteRecordInfo<'/posts/hexo-themes', '/posts/hexo-themes', Record<never, never>, Record<never, never>>,
    '/posts/kirikiroid2-guidance': RouteRecordInfo<'/posts/kirikiroid2-guidance', '/posts/kirikiroid2-guidance', Record<never, never>, Record<never, never>>,
    '/posts/one-click-to-evaluate': RouteRecordInfo<'/posts/one-click-to-evaluate', '/posts/one-click-to-evaluate', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
